library(magrittr, warn.conflicts = FALSE)
library(readr, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)

### PORTASH AUTOGEN START
### The following code has been auto-generated by Portash.
library(optparse, warn.conflicts = FALSE)

arguments <- commandArgs(trailingOnly = TRUE)

optlist <- list(
  make_option("--input", type = "character", help = "The path to a table to be filtered."),
  make_option("--format", type = "character", default = "csv", help = "The format of the input and output files."),
  make_option("--output", type = "character", help = "The path to the output file."),
  make_option("--column_name", type = "character", help = "The name of the column by which to filter."),
  make_option("--value", type = "character", help = "Only rows for which the column contains this value will pass the filter.")
)

parser <- OptionParser(usage = "", option_list = optlist)
par <- parse_args(parser, args = arguments)

# checking inputs
for (required_arg in c("input", "output", "column_name", "value")) {
  if (is.null(par[[required_arg]])) {
    stop('"--', required_arg, '" is a required argument. Use "--help" to get more information on the parameters.')
  }
}
if (!par$format %in% c("csv", "tsv", "rds", "h5")) {
  stop('format must be one of "csv", "tsv", "rds", or "h5".')
}
if (!file.exists(par$input)) {
  stop('input file must exist.')
}
### PORTASH AUTOGEN END

# Import data
read_fun <- switch(
  par$format,
  "csv" = readr::read_csv,
  "tsv" = readr::read_tsv,
  "rds" = readr::read_rds,
  "h5" = stop("h5 files are currently not supported.")
)
table <- read_fun(par$input)

# Filter data.
filtered_table <-
  table %>%
  filter(.data[[par$column_name]] == par$value)

# Write data to file
write_fun <- switch(
  par$format,
  "csv" = readr::write_csv,
  "tsv" = readr::write_tsv,
  "rds" = readr::write_rds,
  "h5" = stop("h5 files are currently not supported.")
)
write_fun(filtered_table, par$output)

