library(magrittr)
library(readr)
library(dplyr)

### PORTASH AUTOGEN START
### The following code has been auto-generated by Portash.
library(argparse)
library(magrittr)

arguments <- commandArgs(trailingOnly = TRUE)

parser <- 
  OptionParser(usage = "")  %>%
  add_option("--input", type = "character", help = "The path to a table to be filtered.") %>%
  add_option("--format", type = "character", default = "csv", help = "The format of the input and output files.") %>%
  add_option("--output", type = "character", help = "The path to the output file.") %>%
  add_option("--column_name", type = "character", help = "The name of the column by which to filter.") %>%
  add_option("--value", type = "character", help = "Only rows for which the column contains this value will pass the filter.")

par <- parse_args(parser, args = arguments)

# checking inputs
if (!par$format %in% c("csv", "tsv", "rds", "h5")) {
  stop('format must be one of "csv", "tsv", "rds", or "h5".')
}
if (!file.exists(par$input)) {
  stop('input file must exist.')
}
### PORTASH AUTOGEN END

# Import data
read_fun <- switch(
  par$format,
  "csv" = readr::read_csv,
  "tsv" = readr::read_tsv,
  "rds" = readr::read_rds,
  "h5" = stop("h5 files are currently not supported.")
)
table <- read_fun(par$input)

# Filter data.
filtered_table <-
  table %>%
  filter(.data[[par$column_name]] == par$value)

# Write data to file
write_fun <- switch(
  par$format,
  "csv" = readr::write_csv,
  "tsv" = readr::write_tsv,
  "rds" = readr::write_rds,
  "h5" = stop("h5 files are currently not supported.")
)
write_fun(filtered_table, par$output)

