### VIASH START
# The following code has been auto-generated by Viash.
import argparse

parser = argparse.ArgumentParser(
  usage = "",
  description = """Prints out the parameter values."""
)
parser.add_argument("--string", type = str, required = False)
parser.add_argument("--real_number", type = float, required = False)
parser.add_argument("--whole_number", type = int, required = False)
parser.add_argument("--truth", action='store_true', required = False)

par = vars(parser.parse_args())

# checking inputs

resources_dir = "."

### VIASH END

for key in par.keys():
	print(key + ": \"" + str(par[key]) + "\"")