#!/bin/bash

# PORTASH START
par_in="input.txt"
par_out="output.txt"
par_filter="AString"
CMDARGS="-b"
# PORTASH END

echo "## Reading from $par_in"
echo "## Filtering for $par_filter"
echo "## Writing to $par_out"
echo "## Additional parameters? $REST"

cat $CMDARGS "$par_in" | grep "$par_filter" > "$par_out"
