#!/bin/bash

# VIASH START
par_in="input.txt"
par_out="output.txt"
par_filter="AString"
PASSTHROUGH="-b"
# VIASH END

echo "## Reading from $par_in"
echo "## Filtering for $par_filter"
echo "## Writing to $par_out"
echo "## Additional parameters? $REST"

cat $PASSTHROUGH "$par_in" | grep "$par_filter" > "$par_out"
